import type { ModuleDefinition } from '../types';

export const PROJECTS_MODULE: ModuleDefinition = {
  id: 'projects',
  name: 'Project Management',
  description: 'Projects, tasks, sprints, automations, and client portals.',
  icon: 'FolderKanban',
  defaultEnabled: true,
  permissionGroups: [
    { id: 'projects',   label: 'Projects' },
    { id: 'tasks',      label: 'Tasks' },
    { id: 'sprints',    label: 'Sprints' },
    { id: 'milestones', label: 'Milestones' },
    { id: 'time',       label: 'Time tracking' },
    { id: 'automation', label: 'Automations' },
    { id: 'portal',     label: 'Client portal' },
    { id: 'docs',       label: 'Docs' },
    { id: 'settings',   label: 'Settings' },
  ],
  permissions: [
    { key: 'projects:view',        label: 'View projects',    defaultRoles: ['admin', 'member'], group: 'projects' },
    { key: 'projects:create',      label: 'Create projects',  defaultRoles: ['admin'],           group: 'projects' },
    { key: 'projects:edit',        label: 'Edit projects',    defaultRoles: ['admin'],           group: 'projects' },
    { key: 'projects:archive',     label: 'Archive projects', defaultRoles: ['admin'],           group: 'projects' },
    { key: 'projects:delete',      label: 'Delete projects',  defaultRoles: ['admin'],           group: 'projects' },
    { key: 'pm.tasks:view',        label: 'View tasks',       defaultRoles: ['admin', 'member'], group: 'tasks' },
    { key: 'pm.tasks:create',      label: 'Create tasks',     defaultRoles: ['admin', 'member'], group: 'tasks' },
    { key: 'pm.tasks:edit',        label: 'Edit tasks',       defaultRoles: ['admin', 'member'], group: 'tasks' },
    { key: 'pm.tasks:assign',      label: 'Assign tasks',     defaultRoles: ['admin'],           group: 'tasks' },
    { key: 'pm.tasks:delete',      label: 'Delete tasks',     defaultRoles: ['admin'],           group: 'tasks' },
    { key: 'pm.sprints:view',      label: 'View sprints',     defaultRoles: ['admin', 'member'], group: 'sprints' },
    { key: 'pm.sprints:manage',    label: 'Manage sprints',   defaultRoles: ['admin'],           group: 'sprints' },
    { key: 'pm.milestones:view',   label: 'View milestones',  defaultRoles: ['admin', 'member'], group: 'milestones' },
    { key: 'pm.milestones:manage', label: 'Manage milestones',defaultRoles: ['admin'],           group: 'milestones' },
    { key: 'pm.time:log',          label: 'Log time',         defaultRoles: ['admin', 'member'], group: 'time' },
    { key: 'pm.time:view_all',     label: 'View all time',    defaultRoles: ['admin'],           group: 'time' },
    { key: 'pm.automations:manage',label: 'Manage automations',defaultRoles: ['admin'],          group: 'automation' },
    { key: 'pm.portal:manage',     label: 'Manage client portal', defaultRoles: ['admin'],       group: 'portal' },
    { key: 'pm.approvals:respond', label: 'Respond to approvals', defaultRoles: ['admin', 'member'], group: 'portal' },
    { key: 'pm.docs:view',         label: 'View docs',        defaultRoles: ['admin', 'member'], group: 'docs' },
    { key: 'pm.docs:edit',         label: 'Edit docs',        defaultRoles: ['admin'],           group: 'docs' },
    { key: 'projects:admin',       label: 'Project settings', defaultRoles: ['admin'],           group: 'settings' },
  ],
  nav: [{ label: 'Projects', path: '/projects', icon: 'FolderKanban' }],
  apiPrefixes: ['/projects', '/pm'],
  workers: ['due-date-alerts', 'overdue-scan', 'health-recalc', 'sprint-rollover'],
  emitsActivity: true,
  emitsAlerts: true,
};
