import type { ModuleDefinition, SubModule } from '../types';

export const FINANCE_MODULE: ModuleDefinition = {
  id: 'finance',
  name: 'Finance',
  description: 'Invoices, payments, expenses, vendors, and AR reports for tenant customers.',
  icon: 'Receipt',
  defaultEnabled: true,
  permissions: [
    { key: 'invoices:view',   label: 'View invoices',   defaultRoles: ['admin', 'member'] },
    { key: 'invoices:create', label: 'Create invoices', defaultRoles: ['admin', 'member'] },
    { key: 'invoices:edit',   label: 'Edit draft invoices', defaultRoles: ['admin', 'member'] },
    { key: 'invoices:delete', label: 'Delete draft invoices', defaultRoles: ['admin'] },
    { key: 'invoices:issue',  label: 'Issue invoices',  defaultRoles: ['admin', 'member'] },
    { key: 'invoices:void',   label: 'Void invoices',   defaultRoles: ['admin'] },
    { key: 'invoices:cancel', label: 'Cancel draft invoices', defaultRoles: ['admin'] },
    { key: 'payments:view',   label: 'View payments',   defaultRoles: ['admin', 'member'] },
    { key: 'payments:create', label: 'Record payments', defaultRoles: ['admin', 'member'] },
    { key: 'payments:refund', label: 'Refund payments', defaultRoles: ['admin'] },
    { key: 'expenses:view',   label: 'View expenses',   defaultRoles: ['admin', 'member'] },
    { key: 'expenses:create', label: 'Create expenses', defaultRoles: ['admin', 'member'] },
    { key: 'expenses:edit',   label: 'Edit expenses',   defaultRoles: ['admin', 'member'] },
    { key: 'expenses:delete', label: 'Delete expenses', defaultRoles: ['admin'] },
    { key: 'vendors:view',   label: 'View vendors',   defaultRoles: ['admin', 'member'] },
    { key: 'vendors:create', label: 'Create vendors', defaultRoles: ['admin', 'member'] },
    { key: 'vendors:edit',   label: 'Edit vendors',   defaultRoles: ['admin', 'member'] },
    { key: 'vendors:delete', label: 'Delete vendors', defaultRoles: ['admin'] },
    { key: 'credit_notes:view',   label: 'View credit notes',   defaultRoles: ['admin', 'member'] },
    { key: 'credit_notes:create', label: 'Create credit notes', defaultRoles: ['admin', 'member'] },
    { key: 'debit_notes:view',   label: 'View debit notes',   defaultRoles: ['admin', 'member'] },
    { key: 'debit_notes:create', label: 'Create debit notes', defaultRoles: ['admin', 'member'] },
    { key: 'reports:view', label: 'View finance reports', defaultRoles: ['admin', 'member'] },
    { key: 'finance:settings', label: 'Manage finance settings', defaultRoles: ['admin'] },
    { key: 'accounting:view', label: 'View chart of accounts and journals', defaultRoles: ['admin', 'member'] },
    { key: 'accounting:manage', label: 'Manage accounts, periods, and journals', defaultRoles: ['admin'] },
    { key: 'documents:view', label: 'View document PDFs', defaultRoles: ['admin', 'member'] },
    { key: 'documents:generate', label: 'Generate document PDFs', defaultRoles: ['admin', 'member'] },
    { key: 'ops:export', label: 'Export tenant data', defaultRoles: ['admin'] },
    { key: 'ops:jobs', label: 'View and replay failed jobs', defaultRoles: ['admin'] },
  ],
  nav: [
    { label: 'Invoices', path: '/finance/invoices', icon: 'FileText' },
    { label: 'Payments', path: '/finance/payments', icon: 'Wallet' },
    { label: 'Expenses', path: '/finance/expenses', icon: 'Receipt' },
    { label: 'Vendors',  path: '/finance/vendors',  icon: 'Building2' },
    { label: 'Chart of Accounts', path: '/finance/accounts', icon: 'BookOpen' },
    { label: 'Journals', path: '/finance/journals', icon: 'List' },
    { label: 'Periods', path: '/finance/periods', icon: 'Calendar' },
    { label: 'Reports',  path: '/finance/reports',  icon: 'BarChart' },
    { label: 'Settings', path: '/finance/settings', icon: 'Settings' },
  ],
  apiPrefixes: [
    '/invoices',
    '/payments',
    '/expenses',
    '/vendors',
    '/credit-notes',
    '/debit-notes',
    '/finance',
    '/accounting',
    '/documents',
  ],
  workers: [],
  emitsActivity: true,
};

export const FINANCE_SUBMODULES: readonly SubModule[] = [
  { id: 'finance:invoices', label: 'Invoices', path: '/finance/invoices', permission: 'invoices:view', legacyModuleId: 'invoices' },
  { id: 'finance:payments', label: 'Payments', path: '/finance/payments', permission: 'payments:view', legacyModuleId: 'payments' },
  { id: 'finance:expenses', label: 'Expenses', path: '/finance/expenses', permission: 'expenses:view', legacyModuleId: 'expenses' },
  { id: 'finance:vendors',  label: 'Vendors',  path: '/finance/vendors',  permission: 'vendors:view',  legacyModuleId: 'vendors' },
  { id: 'finance:accounting', label: 'Accounting', path: '/finance/accounts', permission: 'accounting:view', legacyModuleId: 'accounting' },
  { id: 'finance:documents', label: 'Documents', path: '/finance/invoices', permission: 'documents:view', legacyModuleId: 'documents' },
  { id: 'finance:reports',  label: 'Reports',  path: '/finance/reports',  permission: 'reports:view',  legacyModuleId: 'finance_reports' },
  { id: 'finance:settings', label: 'Settings', path: '/finance/settings', permission: 'finance:settings', legacyModuleId: 'finance_settings' },
];

export const FINANCE_SUBMODULE_IDS: readonly string[] = FINANCE_SUBMODULES.map((s) => s.id);
