import type { ModuleDefinition, SubModule } from '../types';

export const CRM_MODULE: ModuleDefinition = {
  id: 'crm',
  name: 'CRM',
  description: 'Contacts, companies, deals pipeline, and tasks.',
  icon: 'Kanban',
  defaultEnabled: true,
  permissions: [
    { key: 'contacts:view',   label: 'View contacts',   defaultRoles: ['admin', 'member'] },
    { key: 'contacts:create', label: 'Create contacts', defaultRoles: ['admin', 'member'] },
    { key: 'contacts:edit',   label: 'Edit contacts',   defaultRoles: ['admin', 'member'] },
    { key: 'contacts:delete', label: 'Delete contacts', defaultRoles: ['admin'] },
    { key: 'companies:view',   label: 'View companies',   defaultRoles: ['admin', 'member'] },
    { key: 'companies:create', label: 'Create companies', defaultRoles: ['admin', 'member'] },
    { key: 'companies:edit',   label: 'Edit companies',   defaultRoles: ['admin', 'member'] },
    { key: 'companies:delete', label: 'Delete companies', defaultRoles: ['admin'] },
    { key: 'pipelines:view',         label: 'View pipelines & deals',                       defaultRoles: ['admin', 'member'] },
    { key: 'pipelines:create',       label: 'Create deals & records',                       defaultRoles: ['admin', 'member'] },
    { key: 'pipelines:edit',         label: 'Edit deals & records',                         defaultRoles: ['admin', 'member'] },
    { key: 'pipelines:delete',       label: 'Delete deals & records',                       defaultRoles: ['admin'] },
    { key: 'pipelines:config',       label: 'Change pipeline settings (name, description, default)', defaultRoles: ['admin'] },
    { key: 'pipelines:stage.edit',   label: 'Edit stages (rename, reorder, recolor)',       defaultRoles: ['admin', 'member'] },
    { key: 'pipelines:stage.delete', label: 'Delete stages',                                defaultRoles: ['admin'] },
    { key: 'pipelines:field.edit',   label: 'Edit fields (rename, reorder, toggle required, edit options)', defaultRoles: ['admin', 'member'] },
    { key: 'pipelines:field.delete', label: 'Delete fields',                                defaultRoles: ['admin'] },
    { key: 'deals:view',       label: 'View deals',              defaultRoles: ['admin', 'member'] },
    { key: 'deals:create',     label: 'Create deals',            defaultRoles: ['admin', 'member'] },
    { key: 'deals:edit',       label: 'Edit deals',              defaultRoles: ['admin', 'member'] },
    { key: 'deals:delete',     label: 'Delete deals',            defaultRoles: ['admin'] },
    { key: 'deals:move_stage', label: 'Move deal stage',         defaultRoles: ['admin', 'member'] },
    { key: 'deals:win_lose',   label: 'Mark deal won/lost',      defaultRoles: ['admin', 'member'] },
    { key: 'leads:view',    label: 'View leads',    defaultRoles: ['admin', 'member'] },
    { key: 'leads:create',  label: 'Create leads',  defaultRoles: ['admin', 'member'] },
    { key: 'leads:edit',    label: 'Edit leads',    defaultRoles: ['admin', 'member'] },
    { key: 'leads:delete',  label: 'Delete leads',  defaultRoles: ['admin'] },
    { key: 'leads:convert', label: 'Convert leads', defaultRoles: ['admin', 'member'] },
    { key: 'customers:view',   label: 'View customer parties',   defaultRoles: ['admin', 'member'] },
    { key: 'customers:create', label: 'Create customer parties', defaultRoles: ['admin', 'member'] },
    { key: 'customers:edit',   label: 'Edit customer parties',   defaultRoles: ['admin', 'member'] },
    { key: 'customers:delete', label: 'Delete customer parties', defaultRoles: ['admin'] },
    { key: 'customers:merge',  label: 'Merge customer parties',  defaultRoles: ['admin'] },
    { key: 'products:view',   label: 'View products',   defaultRoles: ['admin', 'member'] },
    { key: 'products:create', label: 'Create products', defaultRoles: ['admin', 'member'] },
    { key: 'products:edit',   label: 'Edit products',   defaultRoles: ['admin', 'member'] },
    { key: 'products:delete', label: 'Delete products', defaultRoles: ['admin'] },
    { key: 'quotes:view',   label: 'View quotes',   defaultRoles: ['admin', 'member'] },
    { key: 'quotes:create', label: 'Create quotes', defaultRoles: ['admin', 'member'] },
    { key: 'quotes:edit',   label: 'Edit quotes',   defaultRoles: ['admin', 'member'] },
    { key: 'quotes:delete', label: 'Delete quotes', defaultRoles: ['admin'] },
    { key: 'quotes:send',   label: 'Send quotes',   defaultRoles: ['admin', 'member'] },
    { key: 'quotes:accept', label: 'Accept quotes', defaultRoles: ['admin', 'member'] },
    { key: 'quotes:reject', label: 'Reject quotes', defaultRoles: ['admin', 'member'] },
    { key: 'quotes:cancel', label: 'Cancel quotes', defaultRoles: ['admin'] },
    { key: 'tasks:view',   label: 'View tasks',   defaultRoles: ['admin', 'member'] },
    { key: 'tasks:create', label: 'Create tasks', defaultRoles: ['admin', 'member'] },
    { key: 'tasks:edit',   label: 'Edit tasks',   defaultRoles: ['admin', 'member'] },
    { key: 'tasks:delete', label: 'Delete tasks', defaultRoles: ['admin'] },
  ],
  nav: [
    { label: 'Pipeline',  path: '/crm/pipeline',  icon: 'Kanban' },
    { label: 'Leads',     path: '/crm/leads',     icon: 'UserPlus' },
    { label: 'Customers', path: '/crm/customer-parties', icon: 'Briefcase' },
    { label: 'Contacts',  path: '/crm/contacts',  icon: 'Users' },
    { label: 'Companies', path: '/crm/companies', icon: 'Building2' },
    { label: 'Products',  path: '/crm/products', icon: 'Package' },
    { label: 'Quotes',    path: '/crm/quotes', icon: 'FileText' },
    { label: 'Tasks',     path: '/crm/tasks',     icon: 'CheckSquare' },
  ],
  apiPrefixes: ['/contacts', '/companies', '/deals', '/leads', '/customer-parties', '/customers', '/products', '/quotes', '/pipelines', '/stages', '/items', '/item-groups', '/conversions', '/record-types', '/records', '/tasks'],
  workers: ['task-due-notifier'],
  emitsActivity: true,
};

export const CRM_SUBMODULES: readonly SubModule[] = [
  { id: 'crm:pipeline',  label: 'Pipeline',  path: '/crm/pipeline',  permission: 'pipelines:view', legacyModuleId: 'pipelines' },
  { id: 'crm:leads',     label: 'Leads',     path: '/crm/leads',     permission: 'leads:view', legacyModuleId: 'leads' },
  { id: 'crm:customers', label: 'Customers', path: '/crm/customer-parties', permission: 'customers:view', legacyModuleId: 'customers' },
  { id: 'crm:contacts',  label: 'Contacts',  path: '/crm/contacts',  permission: 'contacts:view',  legacyModuleId: 'contacts'  },
  { id: 'crm:companies', label: 'Companies', path: '/crm/companies', permission: 'companies:view', legacyModuleId: 'companies' },
  { id: 'crm:products',  label: 'Products',  path: '/crm/products', permission: 'products:view', legacyModuleId: 'products' },
  { id: 'crm:quotes',    label: 'Quotes',    path: '/crm/quotes', permission: 'quotes:view', legacyModuleId: 'quotes' },
  { id: 'crm:tasks',     label: 'Tasks',     path: '/crm/tasks',     permission: 'tasks:view',     legacyModuleId: 'tasks'     },
];

export const CRM_SUBMODULE_IDS: readonly string[] = CRM_SUBMODULES.map(s => s.id);
